/* 1. Si existe, la eliminamos (opcional) */
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE ENVIOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF; -- ignora “table not found”
END;
/

---------------------------------------------------------------
-- TABLA ENVIOS 
---------------------------------------------------------------
CREATE TABLE ENVIOS (
  ID               NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
  DESTINATARIO     VARCHAR2(100) NOT NULL,
  PAIS_DESTINO     VARCHAR2(50)  NOT NULL,
  UBICACION_ACTUAL VARCHAR2(100),
  ESTADO           VARCHAR2(20),
  CONSTRAINT PK_ENVIOS PRIMARY KEY (ID)
);

---------------------------------------------------------------
-- 3 registros de ejemplo -------------------------------------
INSERT INTO ENVIOS (DESTINATARIO, PAIS_DESTINO, UBICACION_ACTUAL, ESTADO)
VALUES ('Ana',   'Chile',      'Santiago', 'PENDIENTE');

INSERT INTO ENVIOS (DESTINATARIO, PAIS_DESTINO, UBICACION_ACTUAL, ESTADO)
VALUES ('Luis',  'Perú',       'Lima',     'ENTREGADO');

INSERT INTO ENVIOS (DESTINATARIO, PAIS_DESTINO, UBICACION_ACTUAL, ESTADO)
VALUES ('María', 'Argentina',  'Mendoza',  'TRANSITO');

COMMIT;