/* -------- 1. TABLA PRINCIPAL -------------------------------- */
CREATE TABLE FACTURAS (
  NUMERO      NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
  CLIENTE     VARCHAR2(100)           NOT NULL,
  TOTAL       NUMBER(10,2)            NOT NULL,
  PAGADA      CHAR(1)                 DEFAULT 'N' CHECK (PAGADA IN ('Y','N')),
  CONSTRAINT PK_FACTURAS PRIMARY KEY (NUMERO)
);

/* -------- 2. COLECCIÓN DE SERVICIOS ------------------------- */
CREATE TABLE FACTURA_SERVICIOS (
  FACTURA_NUMERO   NUMBER(19)         NOT NULL,
  SERVICIO         VARCHAR2(100)      NOT NULL,
  CONSTRAINT FK_FS_FACTURA FOREIGN KEY (FACTURA_NUMERO)
      REFERENCES FACTURAS (NUMERO)
      ON DELETE CASCADE
);

/* -------- 3. DATOS DE EJEMPLO (3 facturas) ------------------ */
/*   Factura 1: Cliente Ana, 2 servicios                       */
INSERT INTO FACTURAS (CLIENTE, TOTAL, PAGADA)  VALUES ('Ana',   45000.00, 'N');
INSERT INTO FACTURA_SERVICIOS VALUES (1, 'Consulta general');
INSERT INTO FACTURA_SERVICIOS VALUES (1, 'Vacuna anual');

/*   Factura 2: Cliente Luis, 3 servicios                       */
INSERT INTO FACTURAS (CLIENTE, TOTAL, PAGADA)  VALUES ('Luis',  68500.00, 'Y');
INSERT INTO FACTURA_SERVICIOS VALUES (2, 'Radiografía');
INSERT INTO FACTURA_SERVICIOS VALUES (2, 'Cirugía menor');
INSERT INTO FACTURA_SERVICIOS VALUES (2, 'Medicamentos');

/*   Factura 3: Cliente María, 1 servicio                       */
INSERT INTO FACTURAS (CLIENTE, TOTAL, PAGADA)  VALUES ('María', 25000.00, 'N');
INSERT INTO FACTURA_SERVICIOS VALUES (3, 'Desparasitación');

COMMIT;